### ISSUE TITLE
ERROR: JAVA_HOME is set to an invalid directory: /snap/gradle/120/usr/lib/jvm/default-java

### ISSUE THREAD

**Issue by igfoo** [snapcrafters/gradle#17]
After upgrading to 120 (latest/stable, 7.2), I get
```
$ gradle                                          

ERROR: JAVA_HOME is set to an invalid directory: /snap/gradle/120/usr/lib/jvm/default-java

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

$ ls /snap/gradle/120/usr/lib/jvm/
java-1.16.0-openjdk-amd64  java-16-openjdk-amd64
$ echo $JAVA_HOME

$ 
```

**Comment by dcap0** [comment]
Having the same issue. Since users can't rename files, the symbolic link for `java-1.16.0-openjdk-amd64` should just need a rename to `default-java`, right?

**Comment by dcap0** [comment]
Created Pull Request:
`https://github.com/snapcrafters/gradle/pull/18`

**Comment by tunix** [comment]
I don't know why they left out a symbolic link to default-java 😞 Maybe we should create it ourselves?

**Comment by elect86** [comment]
The snap partition looks like is all read-only, if you want to write anything looks like you have to go through quite some commands :/

**Comment by tunix** [comment]
> The snap partition looks like is all read-only, if you want to write anything looks like you have to go through quite some commands :/

I actually meant to do it inside the PR. JDK for Gradle is bundled into the snap itself and JAVA_HOME points to the bundled JDK. At some point, upstream (or the distro maintainers) broke the symlink we had inside `snapcraft.yml` which causes this issue. We can either place the symlink back inside the snap or define an absolute path to the JDK directory like @dcap0 did in his PR.

**Comment by tunix** [comment]
#18 should fix this. Please reopen otherwise.

**Comment by elect86** [comment]
When will we get the fix downstream?

**Comment by tunix** [comment]
@elect86 - it was actually present in edge channel but i just moved it into stable channel. please check.

**Comment by elect86** [comment]
I have no idea how to force/call an update on snap..

**Comment by elect86** [comment]
It looks like it's solved, thanks for fixing it
